import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

/**
 * Build/dev-time route typegen. Scans the `app/` directory and emits a
 * `solidstep-env.d.ts` that declaration-merges the app's routes into the
 * `Register` interface from `solidstep/router`, so `<Link href>`,
 * `useNavigate(to)`, and `RouteParams`/`PageProps<…>` become route-aware.
 *
 * The pure mapping (`generateRouteTypes`) is split from the Vite-plugin wrapper
 * (`routeTypegen`) so it can be unit-tested without a filesystem.
 */

const PAGE_FILE = /^page\.(tsx|ts|jsx|js)$/;
const isGroupSegment = (seg: string) =>
    seg.startsWith('(') && seg.endsWith(')');
// `_private` dirs and `@slot` parallel-route dirs are not standalone URLs.
const isNonRouteSegment = (seg: string) =>
    seg.startsWith('_') || seg.startsWith('@');
// Single-quoted string literal, safe for any route segment/param name --
// e.g. an apostrophe in a folder name or a kebab-case param key.
const quote = (value: string): string =>
    `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

type RouteInfo = {
    /** Route id keeping bracket syntax, e.g. `/blog/[slug]`. */
    id: string;
    /** href type sources (TS literals/template-literals), e.g. `` `/blog/${string}` ``. */
    hrefs: string[];
    /** Param entries, e.g. `[['slug', 'string']]` or `[['path', 'string[]']]`. */
    params: [string, 'string' | 'string[]'][];
};

/**
 * Map a single app-relative page file path (posix, e.g. `blog/[slug]/page.tsx`)
 * to its route info, or `null` if it isn't a navigable page route (an `@slot`,
 * a `_private` dir, or a non-`page` file).
 */
export const pageFileToRoute = (file: string): RouteInfo | null => {
    const parts = file.split('/');
    const filename = parts[parts.length - 1];
    if (!PAGE_FILE.test(filename)) return null;

    const dirSegments = parts.slice(0, -1);
    if (dirSegments.some(isNonRouteSegment)) return null;

    const urlSegments = dirSegments.filter((s) => !isGroupSegment(s));

    const params: [string, 'string' | 'string[]'][] = [];
    let optionalCatchAll = false;
    const hrefSegments = urlSegments.map((seg) => {
        if (seg.startsWith('[[...') && seg.endsWith(']]')) {
            params.push([seg.slice(5, -2), 'string[]']);
            optionalCatchAll = true;
            return '${string}';
        }
        if (seg.startsWith('[...') && seg.endsWith(']')) {
            params.push([seg.slice(4, -1), 'string[]']);
            return '${string}';
        }
        if (seg.startsWith('[') && seg.endsWith(']')) {
            params.push([seg.slice(1, -1), 'string']);
            return '${string}';
        }
        return seg;
    });

    const id = `/${urlSegments.join('/')}`;
    const hrefBase = `/${hrefSegments.join('/')}`;
    const isDynamic = hrefSegments.some((s) => s.includes('${string}'));
    const hrefs: string[] = [isDynamic ? `\`${hrefBase}\`` : quote(hrefBase)];
    // An optional catch-all also matches its parent path without the segment.
    if (optionalCatchAll) {
        const parent = `/${hrefSegments.slice(0, -1).join('/')}`;
        hrefs.push(quote(parent === '/' ? '/' : parent));
    }

    return { id, hrefs, params };
};

const isValidIdentifier = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
const paramsType = (params: [string, 'string' | 'string[]'][]): string => {
    if (params.length === 0) return '{}';
    return `{ ${params
        .map(([k, t]) => `${isValidIdentifier.test(k) ? k : quote(k)}: ${t}`)
        .join('; ')} }`;
};

/**
 * Generate the `solidstep-env.d.ts` content from a list of app-relative route
 * file paths (posix). Pure — no filesystem access.
 */
export const generateRouteTypes = (files: string[]): string => {
    const routes = files
        .map(pageFileToRoute)
        .filter((r): r is RouteInfo => r !== null)
        // Stable, deterministic order.
        .sort((a, b) => a.id.localeCompare(b.id));

    const ids = routes.map((r) => quote(r.id));
    const hrefs = Array.from(new Set(routes.flatMap((r) => r.hrefs)));
    const paramsEntries = routes.map(
        (r) => `        ${quote(r.id)}: ${paramsType(r.params)};`,
    );

    const routesUnion = ids.length ? ids.join(' | ') : 'never';
    const hrefsUnion = hrefs.length ? hrefs.join(' | ') : 'never';

    return `// AUTO-GENERATED by SolidStep route typegen. Do not edit.
// Regenerated on \`vinxi dev\` / \`vinxi build\`. Safe to delete; will be recreated.
declare module 'solidstep/router' {
    interface Register {
        routes: ${routesUnion};
        hrefs: ${hrefsUnion};
        params: {
${paramsEntries.join('\n')}
        };
    }
}

export {};
`;
};

/** Recursively collect app-relative posix paths of `page.*` files under `dir`. */
const scanPageFiles = (dir: string): string[] => {
    if (!existsSync(dir)) return [];
    const entries = readdirSync(dir, { recursive: true }) as string[];
    return entries
        .map((p) => p.split(/[\\/]/).join('/'))
        .filter((p) => PAGE_FILE.test(p.split('/').pop() ?? ''));
};

/**
 * Vite plugin that (re)generates `solidstep-env.d.ts` for typed routes. Runs on
 * `buildStart` (build + dev initial) and watches `app/` in dev. Add it once to a
 * router's `plugins` array. The file is only rewritten when its content changes,
 * so it never triggers a dev reload loop.
 */
export const routeTypegen = (opts?: {
    appDir?: string;
    outFile?: string;
}): {
    name: string;
    buildStart: () => void;
    configureServer: (server: any) => void;
} => {
    const appDir = opts?.appDir ?? join(process.cwd(), 'app');
    const outFile = opts?.outFile ?? join(process.cwd(), 'solidstep-env.d.ts');

    const run = () => {
        try {
            const content = generateRouteTypes(scanPageFiles(appDir));
            const prev = existsSync(outFile)
                ? readFileSync(outFile, 'utf-8')
                : '';
            if (prev !== content) writeFileSync(outFile, content, 'utf-8');
        } catch {
            // Best-effort: never fail the build/dev server over typegen.
        }
    };

    return {
        name: 'solidstep:route-typegen',
        buildStart() {
            run();
        },
        configureServer(server: any) {
            run();
            const onFsEvent = (file: string) => {
                if (file.replace(/\\/g, '/').includes('/app/')) run();
            };
            server.watcher?.on('add', onFsEvent);
            server.watcher?.on('unlink', onFsEvent);
            server.watcher?.on('addDir', onFsEvent);
            server.watcher?.on('unlinkDir', onFsEvent);
        },
    };
};
